### ISSUE TITLE
transformation not working

### ISSUE THREAD

**Issue by PDabro** [Aelpecyem/Besmirchment#2]
Doing the same method for lycanthropy not working with werepyrism. I can get infected by a werewolf but not working with werepyres. I have only basic Bewitchment and Besmirchment addon installed. I didn't touch any config files. /transformation command working fine, werepyres spawns naturally.

bewitchment version: bewitchment-1.16.5-8 
besmirchment version: besmirchment-1.16.5-2
fabric version: 0.11.3

**Comment by Aelpecyem** [comment]
don't use a pirated client
