### ISSUE TITLE
Apathy prevents altars from gaining power, but is required for lichdom.

### ISSUE THREAD

**Issue by TheOdiumWitch** [Aelpecyem/Besmirchment#4]
In order to become a lich, you need the apathy curse.
You also need 999 altar ME to start the ritual to ascend to lichdom.
The apathy curse prevents the player from having ME.
But it does not prevent the player from draining from the Altar.

**Comment by Aelpecyem** [comment]
This is a Bewitchment-native issue, you should file an issue there instead
