### ISSUE TITLE
Does not run on Dedicated servers due to client-side issues

### ISSUE THREAD

**Issue by MitztheKat** [Aelpecyem/Besmirchment#6]
[2021-05-03-3.log.gz](https://github.com/Aelpecyem/Besmirchment/files/6414979/2021-05-03-3.log.gz)
Hey,
Can you look into dedicated server issues with this mod? I hope this log helps a bit...
And I hope it's the correct log.

**Comment by Aelpecyem** [comment]
that's the wrong log, search in your server folder

**Comment by Aelpecyem** [comment]
your version of Besmirchment was way out of date; BSM 1-2 are not compatbile with BW >=10, use BSM 4
